env:
  browser: true
  es6: true
extends:
  - '@react-native-community'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/react-in-jsx-scope: off
  react-hooks/exhaustive-deps: off
  "@typescript-eslint/explicit-function-return-type": off
settings:
  import/resolver:
    node:
      paths:
        - "./src/*"