env:
  browser: true
  es6: true
extends:
  - '@react-native-community'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
settings:
  import/resolver:
    node:
      paths:
        - "./src/*"