version: '3.1'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: "example"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: 'adminer:latest'
    ports:
      - 8080:8080
    depends_on:
      - postgres
  elasticsearch:
    image: 'elasticsearch:6.4.1'
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: 'kibana:6.4.1'
    ports:
      - 5601:5601
